Отправка формы, получение данных с сервера, отправка формы на сервер,…
htmlacademy-javascript/1336147-keksobooking-23 pull request #11
Opened 2021-07-14 18:00 UTC by iinferus

… проверка данных и вывод сообщений

2021-07-15 06:58 UTC, babtshe requested changes

2021-07-15 06:58 UTC, babtshe commented on js/fetch.js
> +  fetch('https://23.javascript.pages.academy/keksobooking/data')
Хорошо бы вынести в константу.

2021-07-15 06:58 UTC, babtshe commented on js/fetch.js
> +    'https://23.javascript.pages.academy/keksobooking',
❗

2021-07-15 06:58 UTC, babtshe commented on js/message.js
> +  document.addEventListener('click', closeMessage);
Хорошо бы удалять эти обработчики после закрытия окна с сообщением.

2021-07-15 06:58 UTC, babtshe commented on js/message.js
> +  document.addEventListener('click', closeMessage);
❗

2021-07-15 06:58 UTC, babtshe commented on js/offer.js
> +    if(offer.photos === undefined) {
можно обойтись без дополнительного сравнения

2021-07-15 06:58 UTC, babtshe commented on js/offer.js
> +    if (offer.feature === undefined) {
и здесь тоже можно не сравнивать с `undefined`, а сделать как-то так: `if (!someVariable) ...`

2021-07-15 06:58 UTC, babtshe commented on js/util.js
> +};
довольно хрупкая штука. Что если с момента открытия окна в body появится какой-то другой элемент и будет удалён именно он?

2021-07-15 14:23 UTC, iinferus commented on js/message.js
> +  document.addEventListener('click', closeMessage);
Удаление обработчиков добавил на функцию закрытия окна.
Не могу только понять как сделать, что бы eslint не ругался.

2021-07-15 14:38 UTC, babtshe requested changes

2021-07-15 14:38 UTC, babtshe commented on js/fetch.js
> +  fetch('https://23.javascript.pages.academy/keksobooking/data')
константа - адрес запроса, а не функция.

2021-07-16 06:43 UTC, babtshe approved these changes

2021-07-16 06:43 UTC, merged