Случайное число в диапазоне с плавающей точкой
htmlacademy-javascript/1336147-keksobooking-23 pull request #2
Opened 2021-05-29 14:06 UTC by iinferus

2021-05-29 18:10 UTC, babtshe requested changes
Нужно учесть ограничения по диапазону из задания.
![image](https://user-images.githubusercontent.com/30229773/120080579-4b08fa00-c0c2-11eb-981e-420b77917a2a.png)

2021-05-29 18:10 UTC, babtshe commented on js/main.js
> +  return generateNumber;
можно сразу вернуть значение на 3 строке.

2021-05-29 18:10 UTC, babtshe commented on js/main.js
> +function generateGeoCoordinates(minNumber, maxNumber, afterDotNumber) {
Чтобы не указывать количество символов после запятой, можно использовать дефолтное значение параметра функции.

2021-05-31 09:03 UTC, iinferus commented on js/main.js
> +function generateGeoCoordinates(minNumber, maxNumber, afterDotNumber) {
Добавлено дефолтное значение 0

2021-05-31 09:03 UTC, iinferus commented on js/main.js
> +  return generateNumber;
Возвращено значение

2021-05-31 10:14 UTC, babtshe requested changes

2021-05-31 10:14 UTC, babtshe commented on js/main.js
> +  const generateNumber = Math.random() * (maxNumber - minNumber) + minNumber;
стоит обратить внимание на название переменной. Сейчас из названия кажется, что это функция, а на самом деле  это не так.

2021-05-31 10:14 UTC, babtshe commented on js/main.js
> +  }
можно пойти чуть дальше и избавиться от фиксированного порядка аргументов. То есть результат будет выводиться в диапазоне между меньшим и большим аргументами вне зависимости от их порядка. Но это уже на твоё усмотрение, можно и так оставить.

2021-05-31 15:24 UTC, babtshe requested changes

2021-05-31 15:24 UTC, babtshe commented on js/main.js
> +  afterDotNumber = Number(afterDotNumber);
См [критерий](https://up.htmlacademy.ru/javascript/23/criteries#d16)

2021-05-31 15:24 UTC, babtshe commented on js/main.js
> +  return generatedNumber.toFixed(afterDotNumber);
Ход мысли правильный. Осталось добавить маленький штришок. От перестановки слагаемых меняется только знак: 10 - 6 = 4; 4 - 10 = -6. Если использовать модуль числа, то от условия можно будет избавиться. У `Math` есть специальный метод для этого.

2021-06-02 14:54 UTC, babtshe approved these changes

2021-06-02 14:54 UTC, merged