Клонирование карточки объявления с временными данным
htmlacademy-javascript/1336147-keksobooking-23 pull request #6
Opened 2021-06-20 08:03 UTC by iinferus

2021-06-20 09:20 UTC, babtshe requested changes

2021-06-20 09:20 UTC, babtshe commented on js/data.js
> +function generateDataArray(arrayGenerate, arrayCount) {
Здесь хорошо убрать тип данных из названий переменных, вспомнить про критерии именования массивов. Помимо этого можно изменить названия таким образом, чтобы можно было понять, для чего нужны параметры функции, не заглядывая в реализацию.

2021-06-20 09:20 UTC, babtshe commented on js/data.js
> +const locationDataArray = generateDataArray(getLocation,10);
❗

2021-06-20 09:20 UTC, babtshe commented on js/data.js
> +};
Отличное решение! При этом стоит помнить о критериях по записи констант.

2021-06-20 09:20 UTC, babtshe commented on js/main.js
> +import './offer.js';
Есть смысл сделать так, чтобы модули не знали друг про друга и связь между ними была именно в `main.js`. Это упростит дальнейшие правки и в файле не будет импортов, которые никак не используются.

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +  }
такая функция будет заново создаваться для каждого элемента массива. Чтобы экономней расходовать память, стоит вынести её из цикла наружу.

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +      return offerElement.querySelector(`.${selector}`).textContent = element;
см [критерий](https://up.htmlacademy.ru/javascript/23/criteries#d27)

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +  replaceTemplate('popup__text--capacity', `${offer.rooms} комнаты для ${offer.guests} гостей`);
Хорошо бы менять окончания слов в зависимости от числа. Кроме того, можно посмотреть в ТЗ проекта, какие значения могут быть.

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +  function replaceTemplate (selector, element) {
Было бы правильно поменять название параметра. Кажется что должен приходить элемент, а на самом деле приходит строка.

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +      const modifier = item.classList[1];
Довольно хрупкая конструкция. Что будет, если добавятся ещё какие-то классы?

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +      if(!modifiers.includes(modifier)) {
здесь перебор массива в цикле. В нашем проекте это минимальные затраты, но на будущее стоит учесть, что такая операция может быть довольно дорогой.

2021-06-20 09:20 UTC, babtshe commented on js/offer.js
> +  offerList.appendChild(offerElement);
объявление нужно показать только одно.

2021-06-20 13:47 UTC, iinferus commented on js/data.js
> +createAuthor();
Забыл убрать, вызывал, что бы eslint не жаловался.

2021-06-21 14:48 UTC, babtshe requested changes

2021-06-21 14:48 UTC, babtshe commented on js/data.js
> +const OFFER_MAGIC_COUNT = 10;
для чего нужна магия в названии?

2021-06-21 14:48 UTC, babtshe commented on js/data.js
> +const similarOfferData = function (authorData, offerData, locationData) {
глагол из названия функции потерялся. Нужна ли `Data` в названии каждого параметра?

2021-06-21 14:48 UTC, babtshe commented on js/data.js
> +  return [authorData, offerData,locationData];
где-то есть пробелы, где-то нет. Хорошо бы добавить единообразия.

Для чего результат в виде массива возвращается?

2021-06-21 14:48 UTC, babtshe commented on js/data.js
> +const offerDataArray = new Array(OFFER_MAGIC_COUNT).fill(null).map(() => similarOfferData(createAuthor(), createOffer(), getLocation()));
обрати внимание на критерии по именованию массивов.

2021-06-21 14:48 UTC, babtshe commented on js/main.js
> +const generated = generateSimilarAds(offerDataArray);
стоит придумать более информативное название переменной. Кроме того из названия функции следует, что вернётся какой-то массив, а по факту это не так.

2021-06-21 14:48 UTC, babtshe commented on js/offer.js
> +      };
хорошо бы вынести функцию создания строки из цикла. Иначе она инициализируется заново при каждой итерации. Было бы правильно её переиспользовать.

Для 5 комнат результат что-то не очень получается.

2021-06-22 06:46 UTC, babtshe approved these changes

2021-06-22 06:46 UTC, merged