Валидация формы
htmlacademy-javascript/1336147-keksobooking-23 pull request #8
Opened 2021-06-25 13:04 UTC by iinferus

2021-06-28 18:12 UTC, babtshe requested changes

2021-06-28 18:12 UTC, babtshe commented on js/formValidation.js
> +const MAX_PRICE = 1000000;
в принципе дублировать эту проверку в скрипте - избыточно. HTML справляется с такой валидацией без помощи скриптов.

2021-06-28 18:12 UTC, babtshe commented on js/formValidation.js
> +};
Задавать ограничения вручную для каждого случая не лучший способ. Что если гостей будет десяток?
Фактически гостей не может быть больше чем комнат, кроме одного случая.

2021-06-28 18:12 UTC, babtshe commented on js/formValidation.js
> +});
в качестве альтернативы `setCustomValidity` можно выставлять минимальное значение инпута в зависимости от выбранного типа жилья.

2021-06-29 15:06 UTC, babtshe requested changes
![image](https://user-images.githubusercontent.com/30229773/123821767-5be89d80-d904-11eb-83c7-d090dc2ca9c8.png)
Изначально для квартиры минимальная цена указана 5000, только после смены значений меняется на 1000.

Если сначала выставить гостей, а потом уже выбрать количество комнат так, чтобы получить недопустимое значение, то валидация проходит.

В поле адрес неплохо бы что-то записать.

2021-06-30 06:43 UTC, iinferus commented on index.html
> +          <input id="title" name="title" type="text" placeholder="Милая, уютная квартирка в центре Токио" minlength="30" maxlength="100" required value="Милая, уютная квартирка в центре Токио">
А я для теста вставил, что бы каждый раз не писать по 100 раз. Удалил

2021-06-30 06:52 UTC, babtshe requested changes
Стало работать лучше. Осталось поправить ещё такую ситуацию:
![image](https://user-images.githubusercontent.com/30229773/123915124-d4913d80-d988-11eb-89ae-91f115c70106.png)

2021-06-30 15:55 UTC, babtshe requested changes
![image](https://user-images.githubusercontent.com/30229773/123992865-a6394f80-d9d4-11eb-93ca-0a5fcdcc3afa.png)
Форма больше не отправляется, но сообщение об ошибке не соответствует действительности.

2021-07-01 12:59 UTC, babtshe approved these changes

2021-07-01 12:59 UTC, merged